name: "Prepare Zano"
description: "Creates git tab so that Zano could determine it's version"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@zano.org"
        (cd Zano && git tag -a v1.0 -m build HEAD^1)
