name: "Build Android prebuilds"

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Install Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26c
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
      - name: Build
        run: |
          git tag v1.0
          ./build_android_libs.sh
        env:
          ANDROID_NDK_PATH: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Configure git
        run: |
          # Set git credentials
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@zano.org"
      - name: Aquire push lock
        run: |
          attempt=0
          while git ls-remote --exit-code --heads origin push-lock >/dev/null 2>&1 > /dev/null 2>&1; do
            echo "[$(date)]: Waiting for push lock to end"
            sleep 5
            attempt=$((attempt+1))
            if [ $attempt -ge 12 ]; then
              echo "Timeout exceeded"
              exit 1
            fi
          done
          git push origin HEAD:push-lock
      - name: Commit and push artifacts
        run: |
          # Fetch latest changes from remote
          echo "[INFO] Pulling latest changes from remote..."
          git pull

          # Commit if there are changes (even without changes)
          echo "[INFO] Commiting changes"
          git commit --allow-empty -m "[AUTO] build android from ${{ github.sha }}"

          # Check if branch has upstream tracking
          echo "[INFO] Pushing changes"
          git push
      - name: Release push lock
        run: |
          git push origin :push-lock
