name: "Build all Android"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  libopenssl-android:
    name: Build libopenssl Android prebuilds
    uses: ./.github/workflows/libopenssl-android.yml
    secrets: inherit

  libboost-android:
    name: Build libboost Android prebuilds
    uses: ./.github/workflows/libboost-android.yml
    secrets: inherit

  libzano-android:
    name: Build libzano Android prebuilds
    needs: 
      - libboost-android
      - libopenssl-android
    uses: ./.github/workflows/libzano-android.yml
    secrets: inherit
