name: "25 - libboost MacOSX prebuilds"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-libboost-macosx:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1
          submodules: false
      - name: Load env
        uses: ./.github/actions/env
      - name: Cache Boost sources
        uses: actions/cache@v4
        with:
          path: ./thirdparty/boost/boost*.tar.gz
          key: boost-${{ env.BOOST_VERSION }}-${{ env.BOOST_TAR_HASH }}
      - name: Build x86_64
        run: ./thirdparty/boost/macosx/build.sh x86_64
      - name: Build arm64
        run: ./thirdparty/boost/macosx/build.sh arm64
      - name: Build framework
        run: ./thirdparty/boost/macosx/framework.sh
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: _install_macosx/libboost.xcframework
          name: libboost macosx
