name: "25 - libboost Android prebuilds"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-libboost-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1
          submodules: false
      - name: Checkout submodules
        run: |
          git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf "git@github.com:"
          git submodule update --init --depth 1 thirdparty/boost/android/Boost-for-Android
      - name: Setup Android build environment
        id: android
        uses: ./.github/actions/android
      - name: Load env
        uses: ./.github/actions/env
      - name: Build
        run: ./thirdparty/boost/android/build.sh
        env:
          ANDROID_NDK_ROOT: ${{ steps.android.outputs.ndk-path }}
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: _libs_android/boost/arm64-v8a;_libs_android/boost/armeabi-v7a;_libs_android/boost/x86;_libs_android/boost/x86_64;_libs_android/boost/include
          name: libboost android
