name: "25 - libboost iOS prebuilds"

on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: push-artifacts-group

jobs:
  build-libboost-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1
          submodules: false
      - name: Checkout submodules
        run: |
          git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf "git@github.com:"
          git submodule update --init --depth 1 ios-cmake thirdparty/boost/ios/Apple-Boost-BuildScript
      - name: Load env
        uses: ./.github/actions/env
      - name: Build
        run: ./thirdparty/boost/ios/build.sh
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: thirdparty/boost/ios
          name: libboost ios
