name: "25 - libopenssl Windows prebuilds"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-libopenssl-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-latest
            arch: x86_64
            msvc_arch: x64
          - runner: windows-11-arm
            arch: arm64
            msvc_arch: x64_arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 1
          submodules: false
      - name: Load env
        uses: ./.github/actions/env
      - name: Cache OpenSSL sources
        uses: actions/cache@v5
        with:
          path: ./thirdparty/openssl/openssl*.tar.gz
          key: openssl-${{ env.OPENSSL_VERSION }}-${{ env.OPENSSL_TAR_HASH }}
      - name: Build
        run: bash ./thirdparty/openssl/windows/build.sh ${{ matrix.arch }}
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: _install_windows/openssl/${{ matrix.arch }}
          name: libopenssl windows ${{ matrix.arch }}
