name: "25 - libopenssl iOS prebuilds"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-libopenssl-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1
          submodules: false
      - name: Checkout submodules
        run: |
          git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf "git@github.com:"
          git submodule update --init --depth 1 ios-cmake
      - name: Load env
        uses: ./.github/actions/env
      - name: Build iphoneos arm64
        run: ./thirdparty/openssl/ios/build.sh iphoneos arm64
      - name: Build iphonesimulator arm64
        run: ./thirdparty/openssl/ios/build.sh iphonesimulator arm64
      - name: Build iphonesimulator x86_64
        run: ./thirdparty/openssl/ios/build.sh iphonesimulator x86_64
      - name: Build framework
        run: ./thirdparty/openssl/ios/framework.sh
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: thirdparty/openssl/ios/libopenssl.xcframework
          name: libopenssl ios
