name: "25 - libopenssl Linux prebuilds"

on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: push-artifacts-group

jobs:
  build-libopenssl-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 1
          submodules: false
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: g++-aarch64-linux-gnu gcc-aarch64-linux-gnu
          version: 1.0
      - name: Cache OpenSSL sources
        uses: actions/cache@v4
        with:
          path: ./thirdparty/openssl/openssl*.tar.gz
          key: openssl-3.1.8
      - name: Load env
        uses: ./.github/actions/env
      - name: Build
        run: ./thirdparty/openssl/linux/build.sh
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: thirdparty/openssl/linux
          name: libopenssl linux
