name: "25 - libopenssl Android prebuilds"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-libopenssl-android:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86, x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 1
          submodules: false
      - name: Setup Android build environment
        id: android
        uses: ./.github/actions/android
      - name: Load env
        uses: ./.github/actions/env
        with:
          platform: android
      - name: Build
        run: ./thirdparty/openssl/android/build.sh ${{ matrix.arch }}
        env:
          ANDROID_NDK_ROOT: ${{ steps.android.outputs.ndk-path }}
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: _libs_android/openssl/${{ matrix.arch }}
          name: libopenssl android ${{ matrix.arch }}
