name: "20 - libzano Android prebuilds"

on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: push-artifacts-group

jobs:
  build-libzano-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 2
          submodules: recursive
      - name: Setup Android build environment
        id: android
        uses: ./.github/actions/android
      - name: Load env
        uses: ./.github/actions/env
      - name: Build
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@zano.org"
          (cd Zano && git tag -a v1.0 -m build HEAD^1)
          ./android/build.sh
        env:
          ANDROID_NDK_ROOT: ${{ steps.android.outputs.ndk-path }}
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: android
          name: libzano android
