name: "20 - libzano iOS prebuilds"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-libzano-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 2
          submodules: recursive
      - name: Load env
        uses: ./.github/actions/env
        with:
          platform: ios
      - name: Prepare Zano
        uses: ./.github/actions/zano
      - name: Build iphoneos arm64
        run: ./build/ios/build.sh iphoneos arm64
      - name: Build iphonesimulator arm64
        run: ./build/ios/build.sh iphonesimulator arm64
      - name: Build iphonesimulator x86_64
        run: ./build/ios/build.sh iphonesimulator x86_64
      - name: Build framework
        run: ./build/ios/framework.sh
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: _install_ios/lib/libzano.xcframework;_install_ios/lib/libzano-plain-wallet.xcframework
          name: libzano ios
