name: "20 - libzano Android prebuilds"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-libzano-android:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86, x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 2
          submodules: recursive
      - name: Setup Android build environment
        id: android
        uses: ./.github/actions/android
      - name: Load env
        uses: ./.github/actions/env
      - name: Prepare Zano
        uses: ./.github/actions/zano
      - name: Build
        run: ./build/android/build.sh ${{ matrix.arch }}
        env:
          ANDROID_NDK_ROOT: ${{ steps.android.outputs.ndk-path }}
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: _install_android/${{ matrix.arch }};_install_android/include
          name: libzano android ${{ matrix.arch }}
