name: "20 - libzano iOS prebuilds"

on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: push-artifacts-group

jobs:
  build-libzano-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 2
          submodules: recursive
      - name: Load env
        uses: ./.github/actions/env
      - name: Build
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@zano.org"
          (cd Zano && git tag -a v1.0 -m build HEAD^1)
          ./ios/build.sh
      - name: Configure git and stage artifacts for push
        uses: ./.github/actions/artifacts
        with:
          folder: ios
          name: libzano ios
