name: "10 - Build Zano Native Lib"

on:
  workflow_dispatch:

jobs:
  libzano-android:
    uses: ./.github/workflows/libzano-android.yml
    secrets: inherit
  libzano-ios:
    uses: ./.github/workflows/libzano-ios.yml
    secrets: inherit
  libzano-macosx:
    uses: ./.github/workflows/libzano-macosx.yml
    secrets: inherit
  libzano-linux:
    uses: ./.github/workflows/libzano-linux.yml
    secrets: inherit
  libzano-windows:
    uses: ./.github/workflows/libzano-windows.yml
    secrets: inherit
