name: "15 - Build OpenSSL"

on:
  workflow_dispatch:

jobs:
  libopenssl-android:
    uses: ./.github/workflows/libopenssl-android.yml
    secrets: inherit
  libopenssl-ios:
    needs: [libopenssl-android]
    uses: ./.github/workflows/libopenssl-ios.yml
    secrets: inherit
  libopenssl-macosx:
    needs: [libopenssl-ios]
    uses: ./.github/workflows/libopenssl-macosx.yml
    secrets: inherit
  libopenssl-linux:
    needs: [libopenssl-macosx]
    uses: ./.github/workflows/libopenssl-linux.yml
    secrets: inherit
