name: "10 - Build Zano"

on:
  workflow_dispatch:

jobs:
  libzano-android:
    uses: ./.github/workflows/libzano-android.yml
    secrets: inherit
  libzano-ios:
    needs: [libzano-android]
    uses: ./.github/workflows/libzano-ios.yml
    secrets: inherit
  libzano-macosx:
    needs: [libzano-ios]
    uses: ./.github/workflows/libzano-macosx.yml
    secrets: inherit
  libzano-linux:
    needs: [libzano-macosx]
    uses: ./.github/workflows/libzano-linux.yml
    secrets: inherit
