name: "Build prebuilds"

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
      - name: Build
        run: |
          ./build_android_libs.sh
      - name: Commit and push prebuilds
        uses: devops-infra/action-commit-push@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO] "
          commit_message: "build from ${{ github.sha }}"
  # build-macosx:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         lfs: true
  #         submodules: recursive
  #     - name: Build
  #       run: |
  #         ./build_ios_libs.sh
  #     - name: Commit and push prebuilds
  #       uses: devops-infra/action-commit-push@v1.0.3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         commit_prefix: "[AUTO] "
  #         commit_message: "build from ${{ github.sha }}"
